# Generated by Django 3.2 on 2022-10-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product_szie',
            new_name='product_size',
        ),
    ]
